# 1
# print("Hello SoftUni")

# 2
# print(1)
# print(2)
# print(3)
# print(4)
# print(5)
# print(6)
# print(7)
# print(8)
# print(9)
# print(10)

# 3
# side = int(input())
# area = side * side
# print(area)

# 4
# number = float(input())
# cm = number * 2.54
# print(cm)

# 5
# name = input()
# print(f"Hello, {name}!")

# 6
# first_name = input()
# last_name = input()
# age = int(input())
# town = input()
# print(f"You are {first_name} {last_name}, a {age}-years old person from {town}.")

# 7
# name = input()
# count_projects = int(input())
# time_needed = count_projects * 3
# print(f"The architect {name} will need {time_needed} hours to complete {count_projects} project/s.")

# 8
# dogs_count = int(input())
# other_count = int(input())
# dogs_food = dogs_count * 2.50
# other_count = other_count * 4
# final_sum = dogs_food + other_count
# print(f"{final_sum} lv.")

# 9
# square_meters = float(input())
# money_for_landscaping = square_meters * 7.61
# discount = 18/100 * money_for_landscaping
# final_sum = money_for_landscaping - discount
# print(f"The final price is: {final_sum} lv.")
# print(f"The discount is: {discount} lv.")



